/**
 * The Fair: a course of timing, where every hole has something that moves. This file holds the holes that need
 * nothing the engine does not already have (the windmill, the sliding barrier and the conveyor), and the others of the
 * nine are appended as the new kinds of obstacle they use are built. Content only, drawn as `course.ts` explains.
 */
import type { HoleDef } from './course';

export const FAIR: readonly HoleDef[] = [
  {
    name: 'Turnstile',
    par: 2,
    map: [
      '#############',
      '#...........#',
      '#...C.......#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '####.###.####',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...T.......#',
      '#...........#',
      '#############',
    ],
    obstacles: [
      { kind: 'windmill', at: [4, 8], period: 8 },
      { kind: 'windmill', at: [8, 8], period: 8, phase: 0.125 },
    ],
  },
  {
    name: 'Traffic',
    par: 3,
    // far enough that no one stroke reaches the cup, so the first is struck through both barriers and waits for the one moment they are both clear
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [
      { kind: 'barrier', at: [4, 12], length: 1.5, travel: 4.5, period: 4.5 },
      { kind: 'barrier', at: [5, 14], length: 1.5, travel: 4.5, period: 4.5, phase: 0.5 },
    ],
  },
  {
    name: 'The Lift',
    par: 3,
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#111111111#',
      '#~~~~.~~~~#',
      '#~~~~.~~~~#',
      '#~~~~.~~~~#',
      '#~~~~.~~~~#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [{ kind: 'conveyor', from: [5, 9], to: [5, 6], speed: 5 }],
  },
  {
    name: 'Whack-a-mole',
    par: 3,
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [
      { kind: 'barrier', at: [5, 5], length: 1, travel: 5, period: 4 },
      { kind: 'barrier', at: [5, 7], length: 1, travel: 5, period: 4, phase: 1 / 3 },
      { kind: 'barrier', at: [5, 9], length: 1, travel: 5, period: 4, phase: 2 / 3 },
    ],
  },
];
