/**
 * The Fair: a course of timing, where every hole has something that moves. The first four holes need nothing the engine
 * does not already have (the windmill, the sliding barrier and the conveyor), and the last five use the kicker and the
 * moving bumper (a barrier with a post's bounce) too. A barrier's box is the pusher of its own number only while no
 * windmill is listed before it, so a hole lists its barriers first. Content only, drawn as `course.ts` explains.
 */
import { BUMPER } from './arena';
import type { HoleDef } from './course';

export const FAIR: readonly HoleDef[] = [
  {
    name: 'Turnstile',
    par: 2,
    map: [
      '#############',
      '#...........#',
      '#...C.......#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '####.###.####',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...T.......#',
      '#...........#',
      '#############',
    ],
    obstacles: [
      { kind: 'windmill', at: [4, 8], period: 8 },
      { kind: 'windmill', at: [8, 8], period: 8, phase: 0.125 },
    ],
  },
  {
    name: 'Traffic',
    par: 3,
    // far enough that no one stroke reaches the cup, so the first is struck through both barriers and waits for the one moment they are both clear
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [
      { kind: 'barrier', at: [4, 12], length: 1.5, travel: 4.5, period: 4.5 },
      { kind: 'barrier', at: [5, 14], length: 1.5, travel: 4.5, period: 4.5, phase: 0.5 },
    ],
  },
  {
    name: 'The Lift',
    par: 3,
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#111111111#',
      '#~~~~.~~~~#',
      '#~~~~.~~~~#',
      '#~~~~.~~~~#',
      '#~~~~.~~~~#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [{ kind: 'conveyor', from: [5, 9], to: [5, 6], speed: 5 }],
  },
  {
    name: 'Whack-a-mole',
    par: 3,
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [
      { kind: 'barrier', at: [5, 5], length: 1, travel: 5, period: 4 },
      { kind: 'barrier', at: [5, 7], length: 1, travel: 5, period: 4, phase: 1 / 3 },
      { kind: 'barrier', at: [5, 9], length: 1, travel: 5, period: 4, phase: 2 / 3 },
    ],
  },
  {
    name: 'Dodgems',
    par: 3,
    // far enough that the first stroke stops short of the bumpers, and the second goes between them: three bumpers a tile apart, two tiles long, on a four-second beat and out of step by a half and a quarter, so there is a moment all three are off the line at once, as there is not with the thirds the first draft had (it waited out the autopilot's ten seconds and fired blind). A ball that meets one is thrown, not stopped.
    map: [
      '#################',
      '#...............#',
      '#.......C.......#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#.......T.......#',
      '#...............#',
      '#################',
    ],
    obstacles: [
      { kind: 'barrier', at: [8, 5], length: 2, travel: 9, period: 4, phase: 0, bounce: BUMPER.restitution },
      { kind: 'barrier', at: [8, 6], length: 2, travel: 9, period: 4, phase: 0.5, bounce: BUMPER.restitution },
      { kind: 'barrier', at: [8, 7], length: 2, travel: 9, period: 4, phase: 0.25, bounce: BUMPER.restitution },
    ],
  },
  {
    name: 'Carousel',
    par: 3,
    // A belt takes the speed off any ball that meets it and carries it at its own (a spike found that even the hardest putt is stopped within a tile of a belt, and a full ring round an island lets nothing on to it), so the island is a mound of raised grass with no way over it, and the way round is the ride: the south belt carries a ball out to the west flank, the flank carries it up to the back, and the back belt sets it down short of the cup.
    map: [
      '##########',
      '#........#',
      '#.....C..#',
      '#.3333333#',
      '#.3333333#',
      '#.3333333#',
      '#........#',
      '#........#',
      '#........#',
      '#T.......#',
      '#........#',
      '##########',
    ],
    obstacles: [
      { kind: 'conveyor', from: [8, 6], to: [2, 6], speed: 5 },
      { kind: 'conveyor', from: [1, 6], to: [1, 3], speed: 5 },
      { kind: 'conveyor', from: [1, 2], to: [2, 2], speed: 5 },
    ],
  },
  {
    name: 'Ferris',
    par: 3,
    // the wall is raised grass, a wall to the ball, and the one door in it is the windmill's; the kicker stands square behind the door, far enough back that a soft ball dies short of it, so a ball struck hard straight through is thrown back into the blades, and the cup is tucked to one side where only a second stroke, across the room, reaches it
    map: [
      '###########',
      '#.........#',
      '#....k....#',
      '#.........#',
      '#.C.......#',
      '#.........#',
      '#.........#',
      '#3333.3333#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '#.........#',
      '###########',
    ],
    obstacles: [{ kind: 'windmill', at: [5, 7], period: 6 }],
  },
  {
    name: 'Shooting Gallery',
    par: 4,
    // the longest hole of the course: three kickers stand in the field like targets, off the line, and the cup is in a bay whose mouth a barrier slides across
    map: [
      '#############',
      '###.......###',
      '###...C...###',
      '###.......###',
      '###.......###',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#..k........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#........k..#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#..k........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#.....T.....#',
      '#...........#',
      '#...........#',
      '#############',
    ],
    obstacles: [{ kind: 'barrier', at: [6, 4], length: 1.5, travel: 5, period: 5 }],
  },
  {
    name: 'The Big Wheel',
    par: 4,
    // the finale, as The Mill Race has three things: two barriers crossing, a moving bumper, a windmill's door in a wall, and a belt that carries the ball to the cup
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#.........#',
      '#####.#####',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....T....#',
      '###########',
    ],
    obstacles: [
      // the barriers are listed first, since a barrier's box is the pusher of its own number only while no windmill comes before it
      { kind: 'barrier', at: [5, 26], length: 1.5, travel: 4.5, period: 4, phase: 0.25, bounce: BUMPER.restitution },
      { kind: 'barrier', at: [5, 32], length: 1.5, travel: 4.5, period: 5 },
      { kind: 'barrier', at: [5, 31], length: 1.5, travel: 4.5, period: 5, phase: 0.5 },
      { kind: 'windmill', at: [5, 37], period: 8, phase: 0.125 },
      { kind: 'conveyor', from: [5, 4], to: [5, 3], speed: 5 },
    ],
  },
];
