/**
 * The Pinball Shed: banks and bounces, where the rail is a cushion, posts and kickers throw, bumpers slide, a flipper
 * flings, and the player's own line is the game. Every hole is drawn by hand as The Meadow's are (see `course.ts` for the
 * letters), and has one idea and something the player must use or fear. Since 8 October 2026 it is the best seven of its
 * own nine and two of The Fair's, Dodgems and Shooting Gallery, whose bumpers and kickers are pinball's; The Funnel and
 * Plinko went, posts as The Meadow's Bumpers has them, and Plinko's line luck.
 *
 * Without this file the course would have nowhere to be drawn: it is content, and no logic lives in it.
 */

import { BUMPER } from './arena';
import type { HoleDef } from './course';

export const SHED: readonly HoleDef[] = [
  {
    name: 'Corner Pocket',
    par: 2,
    // a wall juts out from the left rail between the tee and the cup, so no straight shot reaches it; a bank off the right rail, and the line goes through the gap and back up past the wall's end
    map: [
      '###########',
      '#.........#',
      '#..C......#',
      '#.........#',
      '######....#',
      '######....#',
      '#.........#',
      '#.......T.#',
      '#.........#',
      '###########',
    ],
  },
  {
    name: 'Half-pipe',
    par: 3,
    // both sides rise in steps to a trough, so a ball struck up the side comes down across it; only a bank, the ground a ball rests on
    map: [
      '#########',
      '#.......#',
      '#...C...#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.......#',
      '#.T.....#',
      '#.......#',
      '#########',
    ],
    terrain: [
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
      '332101233',
    ],
  },
  {
    name: 'The Kicker',
    par: 2,
    // a lane with a kicker square in it and a door in its east wall beside the kicker, the cup in the room beyond, so no straight shot sees the cup: a kicker throws a ball back harder than it met it, so a soft shot into its right cheek is thrown out through the door to the cup, and a hard one straight at it comes back
    map: [
      '###############',
      '####.....######',
      '####.....#...##',
      '####.....#...##',
      '####.......C.##',
      '####..k......##',
      '####.....#...##',
      '####.....######',
      '####.....######',
      '####..T..######',
      '####.....######',
      '###############',
    ],
  },
  {
    name: 'Three Cushion',
    par: 3,
    // the cup is walled in on three sides by raised grass and open only toward the far rail, so the way in is a bank off the rails
    map: [
      '###############',
      '#.............#',
      '#.............#',
      '#.............#',
      '#....3...3....#',
      '#....3.C.3....#',
      '#....33333....#',
      '#..T..........#',
      '#.............#',
      '#.............#',
      '###############',
    ],
  },
  {
    name: 'Dodgems',
    par: 3,
    // far enough that the first stroke stops short of the bumpers, and the second goes between them: three bumpers a tile apart, two tiles long, on a four-second beat and out of step by a half and a quarter, so there is a moment all three are off the line at once, as there is not with the thirds the first draft had (it waited out the autopilot's ten seconds and fired blind). A ball that meets one is thrown, not stopped.
    map: [
      '#################',
      '#...............#',
      '#.......C.......#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#...............#',
      '#.......T.......#',
      '#...............#',
      '#################',
    ],
    obstacles: [
      { kind: 'barrier', at: [8, 5], length: 2, travel: 9, period: 4, phase: 0, bounce: BUMPER.restitution },
      { kind: 'barrier', at: [8, 6], length: 2, travel: 9, period: 4, phase: 0.5, bounce: BUMPER.restitution },
      { kind: 'barrier', at: [8, 7], length: 2, travel: 9, period: 4, phase: 0.25, bounce: BUMPER.restitution },
    ],
  },
  {
    name: 'Flipper Alley',
    par: 3,
    map: [
      '##############',
      '#....#########',
      '#..C.#########',
      '#....#########',
      '#....#########',
      '#....#########',
      '#....#########',
      '#ssss#########',
      '#..........T.#',
      '#............#',
      '##############',
    ],
    obstacles: [{ kind: 'flipper', at: [1, 9], length: 4, swing: 1.3, period: 4, pivot: 'left' }],
  },
  {
    name: 'The Bowl Pit',
    par: 3,
    // a bowl with the cup at the bottom and kickers round its rim: a ball that reaches the rim is kicked back in, and one struck too hard goes up the far side and out over the gap in the rim toward the rail
    map: [
      '###########',
      '#..k...k..#',
      '#.........#',
      '#k.......k#',
      '#.........#',
      '#....C....#',
      '#.........#',
      '#k...k...k#',
      '#.........#',
      '#..k.T.k..#',
      '###########',
    ],
    terrain: [
      '33333333333',
      '33333333333',
      '33222222233',
      '33211111233',
      '33210001233',
      '33210001233',
      '33210001233',
      '33211111233',
      '33222222233',
      '33333333333',
      '33333333333',
    ],
  },
  {
    name: 'Shooting Gallery',
    par: 4,
    // the longest hole of the course: three kickers stand in the field like targets, off the line, and the cup is in a bay whose mouth a barrier slides across
    map: [
      '#############',
      '###.......###',
      '###...C...###',
      '###.......###',
      '###.......###',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#..k........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#........k..#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#..k........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#...........#',
      '#.....T.....#',
      '#...........#',
      '#...........#',
      '#############',
    ],
    obstacles: [{ kind: 'barrier', at: [6, 4], length: 1.5, travel: 5, period: 5 }],
  },
  {
    name: 'Multiball',
    par: 4,
    // everything at once: a jut of rail the way round which is a bank off the east rail, a funnel of posts, a kicker on the line, and at the cup's mouth a flipper whose arm lies across the lane and swings up out of the way
    map: [
      '###########',
      '#.........#',
      '#....C....#',
      '#.........#',
      '###.....###',
      '###.....###',
      '###.....###',
      '#.........#',
      '#..o...o..#',
      '#..o...o..#',
      '#.o.....o.#',
      '#.o.....o.#',
      '#.........#',
      '#....k....#',
      '#.........#',
      '#.........#',
      '######....#',
      '######....#',
      '#.........#',
      '#.T.......#',
      '#.........#',
      '###########',
    ],
    obstacles: [{ kind: 'flipper', at: [3, 5], length: 4, swing: 1.3, period: 4, pivot: 'left' }],
  },
];
